---
- name: Install nginx
  apt:
    name: nginx
    install_recommends: no
    state: present
  notify: restart nginx

- name: Enable service
  systemd:
    name: nginx
    enabled: yes

- name: Edit Nginx main conf Configuration
  template:
    src: templates/etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0600'
